import MasterLayout from '@/components/shared-components/master-Layout/MasterLayout';
import Providers from '@/lib/providers/Provider';
import type { Metadata } from 'next';
import { Noto_Sans, Noto_Sans_Devanagari } from 'next/font/google';
import './globals.css';

const notoSans = Noto_Sans({
  subsets: ['latin'],
  variable: '--font-english', // 👈 ties to your CSS var
});

// Nepali font
const notoNepali = Noto_Sans_Devanagari({
  subsets: ['devanagari'],
  variable: '--font-nepali', // 👈 ties to your CSS var
});
export const metadata: Metadata = {
  title: 'Nagrik App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${notoSans.variable} ${notoNepali.variable} antialiased`}>
        <Providers>
          <MasterLayout>{children}</MasterLayout>
        </Providers>
      </body>
    </html>
  );
}
